# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testId', models.IntegerField()),
                ('time', models.IntegerField()),
                ('value_cold', models.CharField(max_length=30, null=True)),
                ('value_hot', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('testId', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('app_type', models.CharField(blank=True, max_length=32, null=True)),
                ('test_type', models.CharField(blank=True, max_length=32, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32, null=True)),
                ('app_packageName', models.CharField(blank=True, max_length=32, null=True)),
                ('device_name', models.CharField(blank=True, max_length=32, null=True)),
                ('device_version', models.CharField(blank=True, max_length=32, null=True)),
                ('time', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('testId', models.IntegerField()),
                ('log_txt', models.CharField(blank=True, max_length=100)),
                ('img_url', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
